
questions = [
    # 🌎 Silly & Fun Prompts (50)
    'Are there more blades of grass or strands of hair in the world? 🌱💇',
    'Are there more doors or wheels in the world? 🚪🛞',
    'Do you think there are more sand grains or stars? 🌌🏖️',
    'Are there more eyeballs or legs in the world? 👀🦵',
    'Are there more water bottles or phones on Earth? 🍼📱',
    'Is cereal actually a soup? 🥣',
    'Is a hotdog a sandwich? 🌭',
    'Which is worse: soggy fries or cold pizza? 🍟🍕',
    'If you had to eat one food forever, which would it be? 🍽️',
    'Would you rather give up chocolate or cheese forever? 🍫🧀',
    'Would you rather fight 1 horse-sized duck or 100 duck-sized horses? 🐎🦆',
    'Which animal would be the scariest if it could talk? 🐍🐊',
    'Who would win: 1 billion ants or a blue whale? 🐜🐋',
    'If animals could drive cars, which species would be the worst drivers? 🚗🦧',
    'Which would be weirder: flying cows or swimming birds? 🐄🕊️',
    'If you had to shrink one body part by half, which would you pick? 🤔',
    'Which would be harder: no Wi-Fi for a week or no phone battery for a week? 📵🔋',
    'Would you rather always type in ALL CAPS or never use punctuation? 🔠',
    'If your phone could only have one app, which would you keep? 📱',
    'Which emoji best represents your personality today? 😎😂😭',
    'If you could replace all traffic lights with something else, what would it be? 🚦🎨',
    'What’s your current hyperfixation or obsession? 🎨💻',
    'If you could teleport anywhere right now, where would you go? ✈️🌍',
    'Cats 🐱 or dogs 🐶?',
    'What’s the best snack for a late-night gaming session? 🍪🎮',
    'If you could have one useless superpower, what would it be? 🦸‍♂️✨',
    'If your life was a video game, what would its title be? 🎮📀',
    'What song is on repeat for you right now? 🎶🔁',
    'Pineapple on pizza: yes or no? 🍍🍕',
    'You find a mysterious button—do you press it? 🔴🤔',
    'Would you rather be able to fly or be invisible for a day? 🕊️👻',
    'If you could make any animal talk, which would be the funniest? 🐸🤣',
    'What’s the weirdest food combo you actually like? 🤤🍔',
    'Would you rather live underwater or in space? 🌊🚀',
    'Which fictional world would be the most fun to live in? 📺✨',
    'What’s the funniest meme you’ve seen this week? 😂📱',
    'If you could have any cartoon character as a roommate, who would it be? 🏠🎨',
    'Would you rather live without music or without movies? 🎵🎬',
    'If you could rename any animal, which one and what name? 🦒🤪',
    'Would you rather own a dragon or a unicorn? 🐉🦄',
    'Which game character would you trust with your life? 🎮🛡️',
    'If you could turn any activity into an Olympic sport, what would you win gold for? 🏅🎯',
    'Would you rather have a rewind button or a pause button in life? ⏮️⏸️',
    'If you became famous overnight, what would it be for? 🌟📸',
    'Would you rather fight a zombie apocalypse or a robot uprising? 🧟🤖',
    'Which animal would make the best stand-up comedian? 🎤🦙',
    'Would you rather always sneeze glitter or hiccup confetti? 🎉🤧',

    # 🔥 Hypotheticals & Discussion (50)
    'If you could pause time for one hour every day, what would you do during that hour? ⏰✨',
    'You wake up as the opposite gender for 24 hours—what’s the first thing you do? 👩➡️👨',
    'If you could instantly master any skill in the world, which one would you pick? 🎨🎸',
    'You get $10,000 but can only spend it in 24 hours—what do you buy? 💰🛍️',
    'If you could swap lives with any fictional character for a week, who would it be? 🎥📖',
    'You can teleport anywhere, but you can never return to the place you leave. Where’s the first place you go? 🌍✈️',
    'If the internet suddenly disappeared for a week, how would you spend your time? 🌲📴',
    'You can time travel, but only once—do you go to the past or the future? ⏳🔮',
    'If you could speak every language fluently, what would you do first? 🗣️🌐',
    'Imagine Earth gets visited by aliens tomorrow. What’s the first thing you’d ask them? 👽🌎',
    'Would you rather live in a world without music or without video games? 🎵🎮',
    'If you had to delete one app from existence forever, which would it be? 📱🚫',
    'Would you rather always have slow Wi-Fi or always low battery? 📶🔋',
    'Which is better: being rich but unknown, or famous but broke? 💸🌟',
    'Unlimited tacos 🌮 or unlimited pizza 🍕 for life?',
    'What’s a small decision that changed your life in a big way? 🌱✨',
    'If you could redo one day in your life, which would it be? 🔄📅',
    'What’s the most underrated hobby or interest people should try? 🧩🎣',
    'If you had a warning label, what would yours say? ⚠️📝',
    'What’s a childhood dream you still secretly want to achieve? 🌈🚀',
    'If emotions were colors, what color is today for you? 🎨💖',
    'If you had to live in any video game world for a month, which would you choose? 🎮🏰',
    'Would you rather always be 10 minutes late or 20 minutes early? ⏰🤷',
    'If you could swap places with your pet for a day, what would you do? 🐶😹',
    'Which holiday would you celebrate every day if you could? 🎄🎉',
    'Would you rather explore the deep ocean or outer space? 🌊🚀',
    'If you could only keep 3 apps on your phone, which would they be? 📱3️⃣',
    'Would you rather live in the 1800s or 2100s? 🕰️🔮',
    'If you could turn any hobby into a full-time career, what would it be? 🎨🎤',
    'Would you rather never age physically or never age mentally? 🧠💪',
    'If you could add one law to the world, what would it be? ⚖️🌎',
    'If you could have dinner with any fictional character, who would it be? 🍽️📖',
    'Would you rather speak to animals or read minds? 🐕🧠',
    'If you could erase one thing from existence, what would it be? ❌🌍',
    'Would you rather always have perfect weather or never get sick? ☀️💊',
    'If money didn’t exist, what would you spend your life doing? 🏝️🎨',
    'Would you rather always know when someone is lying or get away with every lie? 🤥🕵️',
    'If you could swap lives with a celebrity for a day, who would it be? 🎤🎬',
    'Would you rather have free travel anywhere or free food forever? ✈️🍽️',
    'If you had to live in one season forever, which would you pick? ❄️☀️',
    'Would you rather breathe underwater or fly? 🌊🕊️',
    'If you could revive one extinct animal, which would it be? 🦣🦤',
    'Would you rather live in a treehouse or on a boat? 🌳🚤',
    'If you had to eat the same meal for a month, what would it be? 🍜🍔',
    'Would you rather live with no music or no movies forever? 🎬🚫',
    'If you had a theme song that played every time you entered a room, what would it be? 🎵🚪',
    'Would you rather have a talking pet or a self-cleaning house? 🐕🧹',
    'If you could trade lives with someone in this server for a day, who would it be? 🔄💬',
    'Would you rather only whisper or only shout for the rest of your life? 🤫📢',
]